
stages:
  - build
  - nonprod-deploy

build-stage:
  stage: build
  image: node:latest
  before_script:
    - chmod +x setup_env.sh
    - ./setup_env.sh
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    expire_in: 1 hrs
    paths:
      - build/
  only:
    - master

deploy-stage:
  stage: nonprod-deploy
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  before_script:
    - npm install serverless
    - npm install serverless-s3-sync --save
  script:
    - creds-helper -aws
    - AWS_PROFILE=arnawsiam046711174152rolensgcirole serverless deploy
  dependencies:
    - build-stage
  only:
    - master
