
stages:
  - build
  - update-version
  - nonprod-deploy

build-stage:
  stage: build
  image: node:latest
  before_script:
    - chmod +x setup_env.sh
    - ./setup_env.sh
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    expire_in: 1 hrs
    paths:
      - build/
  only:
    - master

update-version-stage:
  stage: update-version
  image: "gitlab-registry.nordstrom.com/cicd/images/git"
  # when: manual
  variables:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i /tmp/.ssh/id_rsa"
  before_script:
    - mkdir -pvm 0700 /tmp/.ssh
    - echo "$SSH_KEY" > /tmp/.ssh/id_rsa
    - chmod 0400 /tmp/.ssh/id_rsa
  script:
    - python version.py $CI_COMMIT_MESSAGE
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    - git remote set-url --push origin ssh://git@gitlab.nordstrom.com/${CI_PROJECT_PATH}
    - git push -o ci.skip origin vecheka


deploy-stage:
  stage: nonprod-deploy
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  before_script:
    - npm install serverless
    - npm install serverless-s3-sync --save
  script:
    - creds-helper -aws
    - AWS_PROFILE=arnawsiam046711174152rolensgcirole serverless deploy
  dependencies:
    - build-stage
  only:
    - master
