image: node:latest
stages:
  - nonprod
nonprod:
  stage: nonprod
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
  script:
    - CI=false npm run build
    - serverless deploy
