# image: node:latest
# stages:
#   - nonprod
# nonprod:
#   stage: nonprod
#   before_script:
#     - npm config set prefix /usr/local
#     - npm install serverless
#     - npm install
#   script:
#     - CI=false npm run build
#     - npx sls deploy
stages:
  - build
  - nonprod-deploy

build-stage:
  stage: build
  image: node:latest
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    expire_in: 1 hrs
    paths:
      - build/

deploy-stage:
  stage: nonprod-deploy
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  before_script:
    - npm install serverless
  script:
    - creds-helper -aws
    - npm install serverless-s3-sync
    - serverless config credentials --provider aws --key $NIU_App_ID --secret $NIU_App_Secret
    - serverless deploy
  dependencies:
    - build-stage
