# image: node:latest
# stages:
#   - nonprod
# nonprod:
#   stage: nonprod
#   before_script:
#     - npm config set prefix /usr/local
#     - npm install serverless
#     - npm install
#   script:
#     - CI=false npm run build
#     - npx sls deploy

before_script:
  - npm install serverless

stages:
  - nonprod
nonprod-deployment:
  image: gitlab-registry.nordstrom.com/cicd/images/awscli:v1.3
  stage: nonprod
  script:
    - CI=false npm run build
    - npx sls deploy
