# image: node:latest
# stages:
#   - nonprod
# nonprod:
#   stage: nonprod
#   before_script:
#     - npm config set prefix /usr/local
#     - npm install serverless
#     - npm install
#   script:
#     - CI=false npm run build
#     - npx sls deploy
stages:
  - build
  - nonprod-deploy

# build-stage:
#   stage: build
#   image: node:latest
#   script:
#     - npm install
#     - CI=false npm run build
#   artifacts:
#     expire_in: 1 hrs
#     paths:
#       - build/

deploy-stage:
  stage: nonprod-deploy
  image: gitlab-registry.nordstrom.com/cicd/images/incubator/artillery:unstable
  before_script:
    - npm install serverless
    - npm install serverless-s3-sync --save
    # - echo $nsg_application.$ResponseMetadata
    # - echo YAML.load($nsg_application)["ResponseMetadata"]["Credentials"]["SecretAccessKey"]
    # - serverless config credentials --provider aws --key $nsg_application['ResponseMetadata']['Credentials']['AccessKeyId'] --secret $nsg_application['ResponseMetadata']['Credentials']['SecretAccessKey']
  script:
    - creds-helper -aws
    # - serverless deploy
    - slsart deploy
  # dependencies:
  #   - build-stage
