service: nsg-cloud-frontend

frameworkVersion: ">=1.54.0" # for CI job
# frameworkVersion: "=1.60.3"

provider:
  name: aws
  stage: nonprod
  region: us-west-2



resources:
  Resources:
    nsgweb:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.domainName}
        AccessControl: BucketOwnerFullControl
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    nsgwebCloudDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "testing redeployment"
          PriceClass: PriceClass_100
          Aliases:
            - ${self:custom.domainName}
          DefaultRootObject: index.html
          Origins:
            -
              DomainName: !Sub ${self:custom.domainName}.${self:custom.webEndpoint}
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
            # added this here
            -
              DomainName: girm9btzs7.execute-api.us-west-2.amazonaws.com
              Id: APIGatewayOrigin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          CacheBehaviors:
            # added this here
            -
              TargetOriginId: APIGatewayOrigin
              DefaultTTL: 0
              MinTTL: 0
              MaxTTL: 0
              PathPattern: '/nonprod/api/*'
              ViewerProtocolPolicy: https-only
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
              CachedMethods: #cache only on get requests
                - GET
                - HEAD
                - OPTIONS
              Compress: true
              ForwardedValues:
                Headers: #define explicit headers, since API Gateway doesn't work otherwise
                  - Accept-*
                  - Referer
                  - Authorization
                  - Content-Type
                  - Origin
                QueryString: true
            -
              TargetOriginId: S3Origin
              AllowedMethods:
                - GET
                - HEAD
              ForwardedValues:
                QueryString: false
                Cookies:
                 Forward: none
              DefaultTTL: 60
              MinTTL: 60
              MaxTTL: 100
              PathPattern: '/*'
              ViewerProtocolPolicy: redirect-to-https

          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 60
            MinTTL: 60
            MaxTTL: 100
            ForwardedValues:
              QueryString: true
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:046711174152:certificate/5a47ab9f-04ac-405a-b1bc-cf7e45fa589a
            SslSupportMethod: sni-only

    wwwnsgweb:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub www.${self:custom.domainName}
        AccessControl: BucketOwnerFullControl
        WebsiteConfiguration:
          RedirectAllRequestsTo:
            HostName: !Ref nsgweb
            Protocol: http


custom:
  domainName: nsg-nonprod.nordstrom.net
  webEndpoint: s3-website-us-west-2.amazonaws.com
  # uploads npm run build to S3
  s3Sync:
    - bucketName: ${self:custom.domainName}
      localDir: build
      acl: public-read-write

plugins:
  - serverless-s3-sync
