service: orca-frontend

frameworkVersion: ">=1.54.0" # for CI job
# frameworkVersion: "=1.60.3"

provider:
  name: aws
  stage: ${opt:stage, 'nonprod'}
  region: us-west-2

resources:
  Resources:
    nsgweb:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config.${self:provider.stage}.json):domainName}
        AccessControl: BucketOwnerFullControl
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    nsgwebCloudDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "Orca Frontend"
          PriceClass: PriceClass_100
          Aliases:
            - ${file(./config.${self:provider.stage}.json):domainName}
          DefaultRootObject: index.html
          Origins:
            -
              DomainName: !Sub ${file(./config.${self:provider.stage}.json):domainName}.${self:custom.webEndpoint}
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
            # added this here
            -
              DomainName: { 'Fn::ImportValue': 'ApiHostname-v${file(./config.${self:provider.stage}.json):apiVersion}' }
              OriginPath: /${self:provider.stage}
              Id: APIGatewayOrigin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          CacheBehaviors:
            -
              TargetOriginId: S3Origin
              AllowedMethods:
                - GET
                - HEAD
              ForwardedValues:
                QueryString: false
                Cookies:
                 Forward: none
              DefaultTTL: 60
              MinTTL: 60
              MaxTTL: 100
              PathPattern: '/api/doc' ## change from /* to /
              ViewerProtocolPolicy: redirect-to-https
            # added this here
            -
              TargetOriginId: APIGatewayOrigin
              DefaultTTL: 0
              MinTTL: 0
              MaxTTL: 0
              PathPattern: '/api/*'
              ViewerProtocolPolicy: https-only
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
              CachedMethods: #cache only on get requests
                - GET
                - HEAD
                - OPTIONS
              Compress: true
              ForwardedValues:
                Headers: #define explicit headers, since API Gateway doesn't work otherwise
                  - Accept-*
                  - Referer
                  - Authorization
                  - Content-Type
                  - Origin
                QueryString: true
            -
              TargetOriginId: S3Origin
              AllowedMethods:
                - GET
                - HEAD
              ForwardedValues:
                QueryString: false
                Cookies:
                 Forward: none
              DefaultTTL: 60
              MinTTL: 60
              MaxTTL: 100
              PathPattern: '/' ## change from /* to /
              ViewerProtocolPolicy: redirect-to-https

          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 60
            MinTTL: 60
            MaxTTL: 100
            ForwardedValues:
              QueryString: true
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            AcmCertificateArn: ${file(./config.${self:provider.stage}.json):certificate}
            SslSupportMethod: sni-only

    wwwnsgweb:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub www.${file(./config.${self:provider.stage}.json):domainName}
        AccessControl: BucketOwnerFullControl
        WebsiteConfiguration:
          RedirectAllRequestsTo:
            HostName: !Ref nsgweb
            Protocol: http


custom:
  # domainName: orca-nonprod.nordstrom.net
  webEndpoint: s3-website-us-west-2.amazonaws.com
  # apiVersion: 1
  # uploads npm run build to S3
  s3Sync:
    - bucketName: ${file(./config.${self:provider.stage}.json):domainName}
      localDir: build
      acl: public-read-write

plugins:
  - serverless-s3-sync
