export async function postToSlack(location, message) {
  var data = {
    "attachments": [
      {
        "fallback": `Error report generated by ${location.origin}`,
        // "text": "Optional text that should appear within the attachment",
        // "pretext": "Optional text that should appear above the formatted data",
        "color": "#f32013", // Can either be one of 'good', 'warning', 'danger', or any hex color code

        "fields": [
          {
            "title": "Error Report", // The title may not contain markup and will be escaped for you
            "value": `*Origin:* ${location.href}\n*${message}`,
            "short": false // Optional flag indicating whether the `value` is short enough to be displayed side-by-side with other values
          },
        ]
      }
    ]
  }

  await fetch("https://hooks.slack.com/services/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", {
    method: 'POST',
    body: JSON.stringify(data)
  });
}
